#ifndef GNURADIO_FEC_BCH_HPP
#define GNURADIO_FEC_BCH_HPP

#include <array>
#include <bit>
#include <cstddef>
#include <cstdint>
#include <vector>

/**
 * The binary BCH(63,16,23) code, the one protecting P25 Phase 1's network identifier
 * (TIA-102.BAAA).
 *
 * The code is the binary BCH code of length 63 over GF(2^6) generated by x^6 + x + 1, with
 * designed distance 23. Its generator is the least common multiple of the minimal polynomials
 * of alpha^1 through alpha^22; those fall into three cyclotomic cosets of size six and one of
 * size five, so the generator has degree 47 and the code carries 63 - 47 = 16 information
 * bits. Minimum distance 23 means it corrects up to floor((23-1)/2) = 11 bit errors, which is
 * an enormous margin for sixteen bits of payload and is the whole reason a frame layer can
 * afford to treat every frame sync as unproven: a pattern that reached the correlator by
 * accident has essentially no chance of also landing within 11 bits of one of the 65536
 * codewords.
 *
 * The generator is derived here rather than tabulated, because everything it is derived from
 * is stated by the standard — field, primitive polynomial, designed distance — while the
 * polynomial itself is a consequence nobody can check by eye.
 *
 * Decoding is exhaustive nearest-codeword search over all 2^16 codewords rather than an
 * algebraic syndrome decoder. At one identifier per frame — a handful per second at any
 * cadence a protocol defines — an algebraic decoder would buy nothing that matters, and an
 * exhaustive search cannot be wrong about which codeword is nearest. The search may stop at
 * the first codeword within 11 bits: no two codewords are closer than 23 apart, so at most
 * one can lie within 11 of any word, and the first one found is therefore already the unique
 * nearest. A word with no codeword inside 11 is scanned to the end, which both establishes
 * that it is uncorrectable and yields its true distance.
 */
namespace gr::fec {

//! The primitive polynomial generating GF(2^6): x^6 + x + 1.
inline constexpr std::uint8_t kBch63FieldPoly = 0x43U;

//! Code parameters.
inline constexpr unsigned kBch63Length      = 63U;
inline constexpr unsigned kBch63InfoBits    = 16U;
inline constexpr unsigned kBch63ParityBits  = kBch63Length - kBch63InfoBits;
inline constexpr unsigned kBch63Distance    = 23U;
inline constexpr unsigned kBch63Correctable = (kBch63Distance - 1U) / 2U;

namespace detail {

struct Bch63Gf64Tables {
    std::array<std::uint8_t, 126UZ> exp{};
    std::array<std::uint8_t, 64UZ>  log{};
};

//! Powers of the field's primitive element, and their inverse map.
[[nodiscard]] inline constexpr Bch63Gf64Tables bch63Gf64Tables() noexcept {
    Bch63Gf64Tables t{};
    unsigned        x = 1U;
    for (unsigned i = 0U; i < 63U; ++i) {
        t.exp[i] = static_cast<std::uint8_t>(x);
        t.log[x] = static_cast<std::uint8_t>(i);
        x <<= 1U;
        if ((x & 0x40U) != 0U) {
            x ^= static_cast<unsigned>(kBch63FieldPoly);
        }
    }
    for (unsigned i = 63U; i < 126U; ++i) {
        t.exp[i] = t.exp[i - 63U];
    }
    return t;
}

} // namespace detail

//! The generator polynomial, as a bit field in which bit i is the coefficient of x^i.
[[nodiscard]] inline constexpr std::uint64_t bch63GeneratorPoly() noexcept {
    const detail::Bch63Gf64Tables t = detail::bch63Gf64Tables();

    const auto mul = [&t](unsigned a, unsigned b) -> unsigned {
        if (a == 0U || b == 0U) {
            return 0U;
        }
        return t.exp[(static_cast<unsigned>(t.log[a]) + static_cast<unsigned>(t.log[b])) % 63U];
    };

    std::uint64_t generator = 1U;
    std::uint64_t taken     = 0U;

    for (unsigned e = 1U; e < kBch63Distance; ++e) {
        // A cyclotomic coset is closed under doubling the exponent; its least member names it,
        // so each minimal polynomial is multiplied in exactly once.
        unsigned least = e;
        unsigned c     = e;
        do {
            least = (c < least) ? c : least;
            c     = (c * 2U) % 63U;
        } while (c != e);
        if ((taken & (1ULL << least)) != 0U) {
            continue;
        }
        taken |= (1ULL << least);

        // The minimal polynomial of alpha^e is the product of (x + alpha^c) over the coset.
        // Its coefficients lie in GF(2^6) while the product is being formed and in GF(2) once
        // the coset is closed, which is what makes it a binary factor of the generator.
        std::array<unsigned, 8UZ> minimal{};
        minimal[0]      = 1U;
        unsigned degree = 0U;
        c               = e;
        do {
            const unsigned root = t.exp[c];
            for (unsigned i = degree + 1U; i > 0U; --i) {
                minimal[i] = minimal[i - 1U] ^ mul(minimal[i], root);
            }
            minimal[0] = mul(minimal[0], root);
            ++degree;
            c = (c * 2U) % 63U;
        } while (c != e);

        std::uint64_t factor = 0U;
        for (unsigned i = 0U; i <= degree; ++i) {
            if (minimal[i] != 0U) {
                factor |= (1ULL << i);
            }
        }

        std::uint64_t product = 0U;
        for (unsigned i = 0U; i < 64U; ++i) {
            if (((generator >> i) & 1U) != 0U) {
                product ^= (factor << i);
            }
        }
        generator = product;
    }
    return generator;
}

//! The systematic codeword for sixteen information bits: a 63-bit word whose bit 62 is the
//! first bit transmitted, bits 62 down to 47 the information, and bits 46 down to 0 the
//! remainder of the information polynomial divided by the generator.
[[nodiscard]] inline constexpr std::uint64_t bch63Encode(std::uint16_t info) noexcept {
    constexpr std::uint64_t generator = bch63GeneratorPoly();

    const std::uint64_t shifted = static_cast<std::uint64_t>(info) << kBch63ParityBits;
    std::uint64_t       rem     = shifted;
    for (unsigned i = kBch63Length - 1U; i >= kBch63ParityBits; --i) {
        if (((rem >> i) & 1U) != 0U) {
            rem ^= (generator << (i - kBch63ParityBits));
        }
    }
    return shifted | (rem & ((1ULL << kBch63ParityBits) - 1U));
}

//! Every codeword, indexed by its information word. Half a megabyte, built once.
[[nodiscard]] inline const std::vector<std::uint64_t>& bch63Codewords() {
    static const std::vector<std::uint64_t> table = [] {
        std::vector<std::uint64_t> t(std::size_t{1} << kBch63InfoBits);
        for (std::size_t i = 0UZ; i < t.size(); ++i) {
            t[i] = bch63Encode(static_cast<std::uint16_t>(i));
        }
        return t;
    }();
    return table;
}

struct Bch63Result {
    bool          valid{false}; //!< a codeword was found inside the accepted distance
    unsigned      errors{0U};   //!< bits between the received word and the nearest codeword
    std::uint16_t info{0U};     //!< the sixteen information bits of that codeword
};

//! Nearest-codeword decode of a 63-bit received word, bit 62 first transmitted. `maxErrors`
//! may be set below the code's correcting power to trade recovered frames for confidence.
[[nodiscard]] inline Bch63Result bch63Decode(std::uint64_t received, unsigned maxErrors = kBch63Correctable) noexcept {
    const std::vector<std::uint64_t>& table = bch63Codewords();

    unsigned    best      = kBch63Length + 1U;
    std::size_t bestIndex = 0UZ;
    for (std::size_t i = 0UZ; i < table.size(); ++i) {
        const unsigned d = static_cast<unsigned>(std::popcount(table[i] ^ received));
        if (d < best) {
            best      = d;
            bestIndex = i;
            if (d <= kBch63Correctable) {
                break;
            }
        }
    }

    Bch63Result r;
    r.errors = best;
    r.info   = static_cast<std::uint16_t>(bestIndex);
    r.valid  = (best <= maxErrors) && (best <= kBch63Correctable);
    return r;
}

/**
 * The binary BCH codes of length 15 over GF(2^4), the family a link header protected by a short
 * block code is drawn from.
 *
 * The field is GF(2^4) generated by x^4 + x + 1, which is primitive: alpha has order 15, so the
 * fifteen non-zero elements are alpha^0 through alpha^14 and the code length is 15. The generator of
 * the code of designed distance d is the least common multiple of the minimal polynomials of alpha^1
 * through alpha^(d-1), and the exponents fall into the cyclotomic cosets {1,2,4,8}, {3,6,12,9},
 * {5,10} and {7,14,13,11}, each entering the product once. That is the identical construction
 * bch63GeneratorPoly walks at the larger length, so it is written once here as a function of the
 * designed distance and the three codes are three instantiations of it:
 *
 *     d = 3   t = 1   deg g = 4    k = 11    g = x^4 + x + 1
 *     d = 5   t = 2   deg g = 8    k =  7    g = x^8 + x^7 + x^6 + x^4 + 1
 *     d = 7   t = 3   deg g = 10   k =  5    g = x^10 + x^8 + x^5 + x^4 + x^2 + x + 1
 *
 * The true minimum distances equal the designed distances -- 3, 5 and 7 -- so nothing here is a bound
 * the code beats or misses, and the qa establishes that by enumerating every codeword's weight rather
 * than by assertion.
 *
 * Decoding is exhaustive nearest-codeword search, and at this length the argument needs no rate at
 * all: the three tables are 2048, 128 and 32 codewords of fifteen bits, so the whole family is 4416
 * bytes and a compile-time constant. The search may stop at the first codeword within t, because no
 * two codewords are closer than d = 2t + 1 and at most one can therefore lie within t of any received
 * word. A word with no codeword inside t is scanned to the end, which both establishes that it is
 * uncorrectable and yields its true distance.
 *
 * **The distance-3 code is not the tree's landed Hamming(15,11,3).** Its generator is the field
 * polynomial itself, which is the arithmetic saying the distance-3 BCH code of length 15 is a cyclic
 * Hamming code; hamming1511Encode builds a Hamming code from an explicit list of parity columns. The
 * two are equivalent under a permutation of coordinates and their codeword sets are not the same: they
 * share exactly 128 words, a 2^7 subcode of both. So a protocol transmitting a cyclic BCH(15,11,3)
 * codeword cannot be decoded by hamming1511Decode, and the failure is silent -- the wrong decoder
 * finds a nearest codeword, reports zero or one corrected errors, and returns eleven wrong bits. Both
 * ship, and the qa pins the 128.
 */

//! The primitive polynomial generating GF(2^4): x^4 + x + 1.
inline constexpr std::uint8_t kBch15FieldPoly = 0x13U;

//! The code length shared by the family.
inline constexpr unsigned kBch15Length = 15U;

namespace detail {

struct Bch15Gf16Tables {
    std::array<std::uint8_t, 15UZ> exp{};
    std::array<std::uint8_t, 16UZ> log{};
};

//! Powers of the field's primitive element, and their inverse map.
[[nodiscard]] inline constexpr Bch15Gf16Tables bch15Gf16Tables() noexcept {
    Bch15Gf16Tables t{};
    unsigned        x = 1U;
    for (unsigned i = 0U; i < 15U; ++i) {
        t.exp[i] = static_cast<std::uint8_t>(x);
        t.log[x] = static_cast<std::uint8_t>(i);
        x <<= 1U;
        if ((x & 0x10U) != 0U) {
            x ^= static_cast<unsigned>(kBch15FieldPoly);
        }
    }
    return t;
}

} // namespace detail

//! The generator polynomial of the length-15 code of the given designed distance, as a bit field in
//! which bit i is the coefficient of x^i.
[[nodiscard]] inline constexpr std::uint16_t bch15GeneratorPoly(unsigned distance) noexcept {
    const detail::Bch15Gf16Tables t = detail::bch15Gf16Tables();

    const auto mul = [&t](unsigned a, unsigned b) -> unsigned {
        if (a == 0U || b == 0U) {
            return 0U;
        }
        return t.exp[(static_cast<unsigned>(t.log[a]) + static_cast<unsigned>(t.log[b])) % 15U];
    };

    unsigned generator = 1U;
    unsigned taken     = 0U;

    for (unsigned e = 1U; e < distance; ++e) {
        // A cyclotomic coset is closed under doubling the exponent modulo 15; its least member names
        // it, so each minimal polynomial is multiplied in exactly once.
        unsigned least = e;
        unsigned c     = e;
        do {
            least = (c < least) ? c : least;
            c     = (c * 2U) % 15U;
        } while (c != e);
        if ((taken & (1U << least)) != 0U) {
            continue;
        }
        taken |= (1U << least);

        std::array<unsigned, 6UZ> minimal{};
        minimal[0]      = 1U;
        unsigned degree = 0U;
        c               = e;
        do {
            const unsigned root = t.exp[c];
            for (unsigned i = degree + 1U; i > 0U; --i) {
                minimal[i] = minimal[i - 1U] ^ mul(minimal[i], root);
            }
            minimal[0] = mul(minimal[0], root);
            ++degree;
            c = (c * 2U) % 15U;
        } while (c != e);

        unsigned factor = 0U;
        for (unsigned i = 0U; i <= degree; ++i) {
            if (minimal[i] != 0U) {
                factor |= (1U << i);
            }
        }

        unsigned product = 0U;
        for (unsigned i = 0U; i < 16U; ++i) {
            if (((generator >> i) & 1U) != 0U) {
                product ^= (factor << i);
            }
        }
        generator = product;
    }
    return static_cast<std::uint16_t>(generator);
}

struct Bch15Result {
    bool          valid{false}; //!< a codeword was found inside the accepted distance
    unsigned      errors{0U};   //!< bits between the received word and the nearest codeword
    std::uint16_t info{0U};     //!< the information bits of that codeword
};

//! One code of the length-15 family, named by its designed distance: 3, 5 or 7.
template<unsigned Distance>
struct Bch15 {
    static_assert(Distance == 3U || Distance == 5U || Distance == 7U, "the length-15 family is the designed distances 3, 5 and 7");

    static constexpr unsigned      kLength      = kBch15Length;
    static constexpr unsigned      kDistance    = Distance;
    static constexpr std::uint16_t kGenerator   = bch15GeneratorPoly(Distance);
    static constexpr unsigned      kParityBits  = static_cast<unsigned>(std::bit_width(kGenerator)) - 1U;
    static constexpr unsigned      kInfoBits    = kLength - kParityBits;
    static constexpr unsigned      kCorrectable = (Distance - 1U) / 2U;

    //! The systematic codeword: bit 14 is the first bit transmitted, bits 14 down to kParityBits the
    //! information, and the bits below it the remainder of the information polynomial over the generator.
    [[nodiscard]] static constexpr std::uint16_t encode(std::uint16_t info) noexcept {
        const unsigned shifted = (static_cast<unsigned>(info) & ((1U << kInfoBits) - 1U)) << kParityBits;
        unsigned       rem     = shifted;
        for (unsigned i = kLength - 1U; i >= kParityBits; --i) {
            if (((rem >> i) & 1U) != 0U) {
                rem ^= (static_cast<unsigned>(kGenerator) << (i - kParityBits));
            }
        }
        return static_cast<std::uint16_t>(shifted | (rem & ((1U << kParityBits) - 1U)));
    }

    //! Every codeword, indexed by its information word, built at compile time.
    [[nodiscard]] static const std::array<std::uint16_t, 1UZ << kInfoBits>& codewords() noexcept {
        static constexpr std::array<std::uint16_t, 1UZ << kInfoBits> table = [] {
            std::array<std::uint16_t, 1UZ << kInfoBits> built{};
            for (std::size_t i = 0UZ; i < built.size(); ++i) {
                built[i] = encode(static_cast<std::uint16_t>(i));
            }
            return built;
        }();
        return table;
    }

    //! Nearest-codeword decode of a 15-bit received word, bit 14 first transmitted. `maxErrors` may be
    //! set below the code's correcting power to trade recovered blocks for confidence.
    [[nodiscard]] static Bch15Result decode(std::uint16_t received, unsigned maxErrors = kCorrectable) noexcept {
        const std::array<std::uint16_t, 1UZ << kInfoBits>& table = codewords();

        unsigned    best      = kLength + 1U;
        std::size_t bestIndex = 0UZ;
        for (std::size_t i = 0UZ; i < table.size(); ++i) {
            const unsigned d = static_cast<unsigned>(std::popcount(static_cast<unsigned>(table[i] ^ received)));
            if (d < best) {
                best      = d;
                bestIndex = i;
                if (d <= kCorrectable) {
                    break;
                }
            }
        }

        Bch15Result r;
        r.errors = best;
        r.info   = static_cast<std::uint16_t>(bestIndex);
        r.valid  = (best <= maxErrors) && (best <= kCorrectable);
        return r;
    }
};

using Bch15_11 = Bch15<3U>; //!< BCH(15,11,3), the cyclic Hamming code -- not the landed Hamming(15,11,3)
using Bch15_7  = Bch15<5U>; //!< BCH(15,7,5)
using Bch15_5  = Bch15<7U>; //!< BCH(15,5,7)

} // namespace gr::fec

#endif // GNURADIO_FEC_BCH_HPP
