#ifndef GNURADIO_FEC_GOLAY_HPP
#define GNURADIO_FEC_GOLAY_HPP

#include <array>
#include <bit>
#include <cstddef>
#include <cstdint>

/**
 * The binary Golay codes, in the three forms P25 Phase 1 transmits (TIA-102.BAAA).
 *
 * One code underlies all three. The cyclic Golay(23,12,7) code is generated by
 * x^11 + x^10 + x^6 + x^5 + x^4 + x^2 + 1, and every codeword of the extended Golay(24,12,8)
 * code is a Golay(23,12,7) codeword with one further bit appended making the whole word's
 * weight even. Shortening the extended code by holding six information bits at zero gives
 * Golay(18,6,8). So the three forms differ only in how many information bits are carried and
 * whether the overall parity bit is present:
 *
 *   Golay(24,12,8)  12 information + 11 parity + 1 overall parity
 *   Golay(23,12,7)  12 information + 11 parity
 *   Golay(18,6,8)    6 information + 11 parity + 1 overall parity
 *
 * and one decoder serves them all.
 *
 * Decoding is a table lookup because the code is perfect. The 2^11 syndromes of the (23,12)
 * code stand in exact bijection with the 2^11 error patterns of weight three or less —
 * 1 + 23 + 253 + 1771 = 2048 — so every syndrome names one and only one such pattern, and
 * building the table by enumerating those patterns must fill every slot exactly once. That
 * makes the table self-checking: a table with an empty slot or a slot written twice would be
 * a table for a code that is not this one.
 *
 * The consequence for a caller is worth stating plainly, because it is a trap. The (23,12,7)
 * code always decodes: no received word is more than three bits from a codeword, so there is
 * no such thing as a detected-but-uncorrectable error and a word carrying four errors is
 * silently turned into the wrong codeword. What restores a failure signal is the overall
 * parity bit, which is why the codes that carry one report a distance of four as a failure
 * rather than inventing an answer.
 */
namespace gr::fec {

//! The generator polynomial's coefficients, x^11 the high bit.
inline constexpr std::uint32_t kGolayGenerator = 0xC75U;

inline constexpr std::size_t kGolayInfoBits   = 12UZ;
inline constexpr std::size_t kGolayParityBits = 11UZ;
//! Bits the code corrects. Its minimum distance is 7 over 23 bits and 8 over 24.
inline constexpr unsigned kGolayCorrectable = 3U;

//! Reduce a 23-bit word modulo the generator, leaving the 11-bit syndrome.
[[nodiscard]] inline constexpr std::uint32_t golaySyndrome(std::uint32_t word) noexcept {
    std::uint32_t r = word & 0x7FFFFFU;
    for (int bit = 22; bit >= static_cast<int>(kGolayParityBits); --bit) {
        if ((r >> bit) & 1U) {
            r ^= kGolayGenerator << (bit - static_cast<int>(kGolayParityBits));
        }
    }
    return r;
}

//! Encode 12 information bits systematically, the information in bits 22..11.
[[nodiscard]] inline constexpr std::uint32_t golay23Encode(std::uint16_t info) noexcept {
    const std::uint32_t shifted = (static_cast<std::uint32_t>(info) & 0x0FFFU) << kGolayParityBits;
    return shifted | golaySyndrome(shifted);
}

//! Encode 12 information bits into the extended code, the overall parity in bit 0.
[[nodiscard]] inline constexpr std::uint32_t golay24Encode(std::uint16_t info) noexcept {
    const std::uint32_t cw23 = golay23Encode(info);
    return (cw23 << 1) | (static_cast<std::uint32_t>(std::popcount(cw23)) & 1U);
}

//! Encode 6 information bits into the shortened code, an 18-bit codeword.
[[nodiscard]] inline constexpr std::uint32_t golay18Encode(std::uint8_t info) noexcept { return golay24Encode(static_cast<std::uint16_t>(info & 0x3FU)); }

namespace detail {

//! Syndrome to coset leader, one entry per syndrome, built by enumerating every error
//! pattern of weight three or less. Every slot is written exactly once; see the note above.
struct GolayCosetTable {
    std::array<std::uint32_t, 2048UZ> leader{};
    std::array<std::uint8_t, 2048UZ>  written{};
};

[[nodiscard]] inline constexpr GolayCosetTable buildGolayCosetTable() noexcept {
    GolayCosetTable t{};
    const auto      place = [&t](std::uint32_t pattern) constexpr noexcept {
        const std::uint32_t s = golaySyndrome(pattern);
        t.leader[s]           = pattern;
        ++t.written[s];
    };
    place(0U);
    for (int a = 0; a < 23; ++a) {
        place(1U << a);
        for (int b = a + 1; b < 23; ++b) {
            place((1U << a) | (1U << b));
            for (int c = b + 1; c < 23; ++c) {
                place((1U << a) | (1U << b) | (1U << c));
            }
        }
    }
    return t;
}

inline constexpr GolayCosetTable kGolayCoset = buildGolayCosetTable();

} // namespace detail

//! Whether the coset table is the bijection a perfect code demands. A caller has no reason
//! to ask, but a test does: this is the property that makes the decoder's table the right
//! table rather than merely a table.
[[nodiscard]] inline constexpr bool golayCosetTableIsBijective() noexcept {
    for (const std::uint8_t n : detail::kGolayCoset.written) {
        if (n != 1U) {
            return false;
        }
    }
    return true;
}

struct GolayResult {
    std::uint16_t info{0U};     //!< the recovered information bits, right-aligned
    unsigned      errors{0U};   //!< bits corrected, or the distance found when it failed
    bool          valid{false}; //!< the word lay inside the code's correcting radius
};

//! Decode a 23-bit codeword, its first transmitted bit in bit 22.
//!
//! This form has no failure mode: the code is perfect, so `valid` is always true and a word
//! carrying more than three errors decodes to a neighboring codeword rather than reporting
//! anything. Use the extended forms where a failure signal is wanted.
[[nodiscard]] inline GolayResult golay23Decode(std::uint32_t cw) noexcept {
    const std::uint32_t word       = cw & 0x7FFFFFU;
    const std::uint32_t correction = detail::kGolayCoset.leader[golaySyndrome(word)];

    GolayResult r;
    r.info   = static_cast<std::uint16_t>(((word ^ correction) >> kGolayParityBits) & 0x0FFFU);
    r.errors = static_cast<unsigned>(std::popcount(correction));
    r.valid  = true;
    return r;
}

//! Decode a 24-bit extended codeword, its first transmitted bit in bit 23 and the overall
//! parity in bit 0.
//!
//! The overall parity is what turns the perfect inner code into one that can say no. Three
//! errors among the 23 coded bits are corrected by the table; a fourth shows up as an overall
//! parity that disagrees with the corrected word, and beyond the code's distance of 8 there
//! is nothing to be done but report it.
[[nodiscard]] inline GolayResult golay24Decode(std::uint32_t cw) noexcept {
    const std::uint32_t word       = (cw >> 1) & 0x7FFFFFU;
    const std::uint32_t overall    = cw & 0x1U;
    const std::uint32_t correction = detail::kGolayCoset.leader[golaySyndrome(word)];
    const std::uint32_t corrected  = word ^ correction;

    const unsigned inner    = static_cast<unsigned>(std::popcount(correction));
    const bool     parityOk = ((static_cast<std::uint32_t>(std::popcount(corrected)) & 1U) == overall);

    GolayResult r;
    r.info   = static_cast<std::uint16_t>((corrected >> kGolayParityBits) & 0x0FFFU);
    r.errors = inner + (parityOk ? 0U : 1U);
    r.valid  = (r.errors <= kGolayCorrectable);
    return r;
}

//! Decode an 18-bit shortened codeword, its first transmitted bit in bit 17.
//!
//! Six information bits are carried and the other six are held at zero by both ends. A
//! decode whose corrected word puts anything in those six has followed its syndrome out of
//! the shortened code, which cannot have been transmitted — so the word is reported invalid
//! rather than having its high bits discarded. Discarding them costs the layer above a
//! failure signal it can use, since a symbol known to be doubtful is worth more to a
//! Reed-Solomon decoder than one silently guessed.
[[nodiscard]] inline GolayResult golay18Decode(std::uint32_t cw) noexcept {
    GolayResult r = golay24Decode(cw & 0x3FFFFU);
    if ((r.info & 0x0FC0U) != 0U) {
        r.valid  = false;
        r.errors = kGolayCorrectable + 1U;
    }
    r.info &= 0x3FU;
    return r;
}

} // namespace gr::fec

#endif // GNURADIO_FEC_GOLAY_HPP
